stages:
  data_ingestion:
    cmd: python src/SMSClassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/SMSClassifier/pipeline/stage_01_data_ingestion.py
    outs:
      - artifacts/data_ingestion/SMS-Spam.zip
      - artifacts/data_ingestion/SMS-Spam

  data_validation:
    cmd: python src/SMSClassifier/pipeline/stage_02_data_validation.py
    deps:
      - src/SMSClassifier/pipeline/stage_02_data_validation.py
      - config/config.yaml
      - artifacts/data_ingestion/SMS-Spam
    outs:
      - artifacts/data_validation/status.txt

  data_transformation:
    cmd: python src/SMSClassifier/pipeline/stage_03_data_transformation.py
    deps:
      - src/SMSClassifier/pipeline/stage_03_data_transformation.py
      - artifacts/data_ingestion/SMS-Spam/spam.csv
    outs:
      - artifacts/data_transformation/train.csv
      - artifacts/data_transformation/test.csv

  # model_training:
  #   cmd: python src/SMSClassifier/pipeline/stage_04_model_training.py
  #   deps:
  #     - src/SMSClassifier/pipeline/stage_04_model_training.py
  #     - artifacts/data_transformation/clean_df.csv
  #   outs:
  #     - artifacts/model_training/tfidfv.joblib
  #     - artifacts/model_training/model.joblib
