stages:
  data_ingestion:
    cmd: python src/SMSClassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/SMSClassifier/pipeline/stage_01_data_ingestion.py
    outs:
      - artifacts/data_ingestion/SMS-Spam.zip
      - artifacts/data_ingestion/SMS-Spam