stages:
  data_ingestion:
    cmd: python src/SMSClassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/SMSClassifier/pipeline/stage_01_data_ingestion.py
    outs:
      - artifacts/data_ingestion/SMS-Spam.zip
      - artifacts/data_ingestion/SMS-Spam

  data_validation:
    cmd: python src/SMSClassifier/pipeline/stage_02_data_validation.py
    deps:
      - src/SMSClassifier/pipeline/stage_02_data_validation.py
      - config/config.yaml
      - artifacts/data_ingestion/SMS-Spam
    outs:
      - artifacts/data_validation/status.txt
