artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  data_url: https://github.com/FraidoonOmarzai/data/raw/main/SMS-Spam.zip
  local_data_file: artifacts/data_ingestion/SMS-Spam.zip
  unzip_dir: artifacts/data_ingestion