artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  data_url: https://github.com/FraidoonOmarzai/data/raw/main/SMS-Spam.zip
  local_data_file: artifacts/data_ingestion/SMS-Spam.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_dir: artifacts/data_ingestion/SMS-Spam
  status: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/SMS-Spam/spam.csv

model_training:
  root_dir: artifacts/model_training
  df: artifacts/data_transformation/clean_df.csv