artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  data_url: https://github.com/FraidoonOmarzai/data/raw/main/SMS-Spam.zip
  local_data_file: artifacts/data_ingestion/SMS-Spam.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_dir: artifacts/data_ingestion/SMS-Spam
  status: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/SMS-Spam/spam.csv

model_training:
  root_dir: artifacts/model_training
  train_path: artifacts/data_transformation/train.csv

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_training/model.joblib
  experiment_name: SMS-Classifier-exp
  mlflow_uri: https://dagshub.com/fraidoon_omarzai/end-to-end-SMS-Spam-classifier.mlflow
  run_name: Multinomial
  metric_file_name: artifacts/model_evaluation/metrics.json
